plugins:
  youtube:
    pot:
      token: 0123456789
      visitorData: 0123456789
  lavasrc:
    spotify:
      clientId: 0123456789
      clientSecret: 0123456789
      spDc: 0123456789
    deezer:
      masterDecryptionKey: 0123456789 # the master key used for decrypting the deezer tracks. (yes this is not here you need to get it from somewhere else)
      arl: "0123456789"
    tidal:
      countryCode: "DE" # the country code for accessing region-specific content on Tidal (ISO 3166-1 alpha-2).
      searchLimit: 6 # How many search results should be returned
      token: 0123456789 # the token used for accessing the tidal api. See https://github.com/topi314/LavaSrc#tidal

lavalink:
  server:
    password: "youshallnotpass2"